  {
"openapi": "3.0.3",
"info": {

  "title": "Todolist RESTful API",
  "description": "OpenAPI for Todolist",
  "version": "1",
  "contact": {
    "name": "Jabriel Hans Sikma",
  },
  'license':
    {
      name: "Apache 2.0"
    }
},
"servers":[
  {
    "url": "https://{environment}.jirbthagoras.com/api/v1",
    "description": 'Todolist RESTful API',
    "variables":
      {
        "environment": {
                         "default": "dev",
                         "description": 'Server Environment',
                         "enum":
                           [
                           "dev",
                           "qa",
                           'prod'
                           ]
        }
      },
  }
],
"paths": {
           "/todolist": {
                          "get": {
                                   security:
                                     [

                                       {
                                         "TodolistAuth": [],
                                       }

                                     ],
                                   tags: ['Todolist'],
                                   summary: "Get All Active Todolist",
                                   description: 'Get All Active Todolist By Default',
                                   responses:
                                     {
                                       "200":
                                         {
                                           "description": "Succes get all Todolist",
                                           "content":
                                             {
                                               "application/json":
                                               {
                                                 'schema':
                                                   {

                                                     $ref: "#/components/schemas/ArrayTodolist"

                                                   }
                                               ,
                                                 examples:
                                                   {
                                                     'success': {
                                                                  description: 'Sucess get all todolist',
                                                                  "value":
                                                                    [
                                                                      {
                                                                        "id": "1",
                                                                        'name': "Java",
                                                                        "priority": 3,
                                                                        "tags": ["Java", "Programming"]
                                                                      }
                                                                    ]
                                                     }
                                                   }
                                               }
                                             }
                                         }
                                     },
                                   parameters:
                                     [

                                       {
                                         'name': 'Include Done',
                                         'required': false,
                                         description: 'Is include done todolist',
                                         in: query,
                                         "schema":
                                           {
                                             type: boolean,
                                             default: true,
                                             nullable: true
                                           }

                                       },

                                       {
                                         'name': 'name',
                                         'required': false,
                                         description: 'Filter todolist by name',
                                         in: query,
                                         "schema":
                                           {
                                             type: string,
                                             "nullable": true,
                                             maxLength: 100,
                                             minLength: 1

                                           },
                                         "examples":
                                           {
                                             "java":
                                               {
                                                 description: "Example Java",
                                                 value: 'Java',
                                               },
                                             "php":
                                               {
                                                 description: "Example PHP",
                                                 value: 'PHP',
                                               }
                                           }
                                       }

                                     ]
                          },
                          "post": {
                            security:
                                    [

                                      {
                                        "TodolistAuth": [ ],
                                      }

                                    ],
                                    summary: "Create new Todolist",
                                    tags: ['Todolist'],
                                    description: "Create new todolist and write in database",
                                    responses:
                                      {
                                        "200":
                                          {
                                            description: "Succes create todolist",
                                            content:
                                              {
                                                "application/json":
                                                  {
                                                    'schema':
                                                      {
                                                        $ref: "#/components/schemas/ArrayTodolist",
                                                      }
                                                  ,
                                                    examples:
                                                      {
                                                        "java":
                                                          {
                                                            description: "Created Java Todolist",
                                                            "value":
                                                              {
                                                                "id": '1',
                                                                "name": "Java",
                                                                "priority": 2,
                                                                "tags": ["Java", 'Programming']
                                                              }
                                                          },
                                                        "php":
                                                          {
                                                            description: "Created PHP Todolist",
                                                            "value":
                                                              {
                                                                "id": '1',
                                                                "name": "PHP",
                                                                "priority": 2,
                                                                "tags": ["PHP", 'Programming']
                                                              }
                                                          }
                                                      }
                                                  }
                                              }
                                          }
                                      },
                                    requestBody:
                                      {
                                        required: true,
                                        content:
                                          {
                                            "application/json":
                                              {
                                                schema:
                                                  {
                                                    $ref: "#/components/schemas/CreateOrUpdateTodolist",
                                                  }
                                              ,
                                                examples:
                                                  {
                                                    "java":
                                                      {
                                                        "value": {
                                                                   name: "Belajar bahasa pemrograman Java",
                                                                   priority: 3,
                                                                   tags: ['Java', 'Programming'],
                                                        }
                                                      },
                                                    "php":
                                                      {
                                                        "value": {
                                                                   name: "Belajar bahasa pemrograman PHP",
                                                                   priority: 1,
                                                                   tags: ['PHP', 'Programming']
                                                        }
                                                      }
                                                  }
                                              }
                                          }
                                      }

                          },
           },
           "/todolist/{todolistId}": {
                          "delete":
                            {
                              security:
                                [

                                  {
                                    "TodolistAuth": [ ],
                                  }

                                ],
                              summary: "Delete active todolist",
                              tags: ['Todolist'],
                              description: "Delete Active todolist from database",
                              responses:
                                {
                                  "200": {
                                           description: "Success delete todolist",
                                           content:
                                             {
                                               "application/json":
                                                 {
                                                   schema:
                                                     {
                                                       type: "object",
                                                       "properties":
                                                         {
                                                           "success": {
                                                                        type: boolean
                                                           }
                                                         }
                                                     }
                                                 }
                                             }
                                  },
                                  "404":
                                    {
                                      description: "Failed to update the todolist",
                                      content:
                                        {
                                          "application/json":
                                            {
                                              schema:
                                                {
                                                  type: object,
                                                  properties:
                                                    {
                                                      "success":
                                                        {
                                                          type: boolean,
                                                          default: false
                                                        }
                                                    }
                                                },
                                              examples:
                                                {
                                                  'success':
                                                    {
                                                      "description": "Sample failed update todolist",

                                                    }
                                                }
                                            }
                                        }
                                    }
                                },
                              parameters:
                                [

                                  {
                                    "$ref": "#/components/parameters/TodolistId"
                                  }

                                ]
                            },
                          "put":
                            {

                              summary: "Update active todolist",
                              tags: ['Todolist'],
                              description: "Update Active todolist in database",
                              responses:
                                {
                                  "200":
                                    {
                                      description: "Succes create todolist",
                                      content:
                                        {
                                          "application/json":
                                            {
                                              'schema':
                                                {
                                                  $ref: "#/components/schemas/ArrayTodolist",
                                                }
                                              ,
                                              examples:
                                                {
                                                  "java":
                                                    {
                                                      description: "Created Java Todolist",
                                                      "value":
                                                        {
                                                          "id": '1',
                                                          "name": "Java",
                                                          "priority": 2,
                                                          "tags": [ "Java", 'Programming' ]
                                                        }
                                                    },
                                                  "php":
                                                    {
                                                      description: "Created PHP Todolist",
                                                      "value":
                                                        {
                                                          "id": '1',
                                                          "name": "PHP",
                                                          "priority": 2,
                                                          "tags": [ "PHP", 'Programming' ]
                                                        }
                                                    }
                                                }
                                            }
                                        }
                                    }
                                },
                              requestBody:
                                {
                                  required: true,
                                  content:
                                    {
                                      "application/json": {
                                                            schema:
                                                              {

                                                                $ref: "#/components/schemas/CreateOrUpdateTodolist"
                                                              },
                                                            examples:
                                                              {
                                                                'java':
                                                                  {
                                                                    "description": "Sample param Java",
                                                                    value: '1',
                                                                  },
                                                                'php':
                                                                  {
                                                                    "description": "Sample param PHP",
                                                                    value: '1',
                                                                  }
                                                              }
                                      }
                                    }
                                },
                              parameters:
                                [

                                  {

                                    $ref: "#/components/parameters/TodolistId",
                                  }


                                ]

                            }
           }
},
components:
  {
    securitySchemes:
      {
        "TodolistAuth":
          {
            "type": "apiKey",
            "description": "Authentication for Todolist API",
            "in": "header",
            'name': 'X-TL-APIKEY'
          }
      },
    parameters:
      {

        "TodolistId":
          {
            name: "todolistId",
            "description": 'Id for updating todolist',
            in: "path",
            required: true,
            schema:
              {

                type: string,
                minLength: 1,
                maxLength: 100,

              },
            examples:
              {
                "java": {
                  description: "Sample Java todolist",
                  "value": 1
                }
              }


          },

      },
    schemas:
      {
        "Todolist":
          {
            type: object,
            "properties":
              {
                'id': {
                  type: string,
                },
                'name': {
                  type: string,
                },
                'priority': {
                  type: number,
                  format: "int32",
                },
                'tags': {
                  type: array,
                  items:
                    {
                      type: string
                    }
                }
              }
          },
        "CreateOrUpdateTodolist":
          {
            type: object,
            "properties":
              {
                'name': {
                  type: string,
                },
                'priority': {
                  type: number,
                  format: "int32",
                },
                'tags': {
                  type: array,
                  items:
                    {
                      type: string
                    }
                }
              }
          },
        "ArrayTodolist":
          {
            type: array,
            items:
              {
                type: object,
                "properties":
                  {
                    'name': {
                      type: string,
                    },
                    'priority': {
                      type: number,
                      format: "int32",
                    },
                    'tags': {
                      type: array,
                      items:
                        {
                          type: string
                        }
                    }
                  }
              }
          }
      }
  }

}